https://en.wikipedia.org/wiki/Main_page
https://en.wikipedia.org/wiki/Despacito
https://en.wikipedia.org/wiki/Youtube
https://en.wikipedia.org/wiki/Wikipedia:Most_popular_pages_October_2001
https://en.wikipedia.org/wiki/Usenet_cabal
https://en.wikipedia.org/wiki/Main_Page
https://en.wikipedia.org/wiki/Special:Search
https://en.wikipedia.org/wiki/Special:Random
https://en.wikipedia.org/wiki/Undefined
https://en.wikipedia.org/wiki/-
https://en.wikipedia.org/wiki/Special:Random
https://en.wikipedia.org/wiki/Special:Watchlist
https://en.wikipedia.org/wiki/Wiki
https://en.wikipedia.org/wiki/Facebook
https://en.wikipedia.org/wiki/YouTube
https://en.wikipedia.org/wiki/404.php
https://en.wikipedia.org/wiki/United_States
https://en.wikipedia.org/wiki/XHamster
https://en.wikipedia.org/wiki/Special:Book
https://en.wikipedia.org/wiki/Search
https://en.wikipedia.org/wiki/Portal:Current_events
https://en.wikipedia.org/wiki/Google
https://en.wikipedia.org/wiki/Donald_Trump
https://en.wikipedia.org/wiki/Wikipedia:Your_first_article
https://en.wikipedia.org/wiki/Wikipedia
https://en.wikipedia.org/wiki/Special:CreateAccount
https://en.wikipedia.org/wiki/Barack_Obama
https://en.wikipedia.org/wiki/India
https://en.wikipedia.org/wiki/World_War_II
https://en.wikipedia.org/wiki/Special:RecentChanges
https://en.wikipedia.org/wiki/Michael_Jackson
https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License
https://en.wikipedia.org/wiki/United_Kingdom
https://en.wikipedia.org/wiki/Eminem
https://en.wikipedia.org/wiki/Wsearch.php
https://en.wikipedia.org/wiki/Lady_Gaga
https://en.wikipedia.org/wiki/Sex
https://en.wikipedia.org/wiki/Malware
https://en.wikipedia.org/wiki/The_Beatles
https://en.wikipedia.org/wiki/Adolf_Hitler
https://en.wikipedia.org/wiki/Game_of_Thrones
https://en.wikipedia.org/wiki/Justin_Bieber
https://en.wikipedia.org/wiki/World_War_I
https://en.wikipedia.org/wiki/Elizabeth_II
https://en.wikipedia.org/wiki/Cristiano_Ronaldo
https://en.wikipedia.org/wiki/The_Big_Bang_Theory
https://en.wikipedia.org/wiki/Steve_Jobs
https://en.wikipedia.org/wiki/Canada
https://en.wikipedia.org/wiki/Portal:Contents
https://en.wikipedia.org/wiki/Kim_Kardashian
https://en.wikipedia.org/wiki/Australia
https://en.wikipedia.org/wiki/Stephen_Hawking
https://en.wikipedia.org/wiki/Lil_Wayne
https://en.wikipedia.org/wiki/Academy_Awards
https://en.wikipedia.org/wiki/How_I_Met_Your_Mother
https://en.wikipedia.org/wiki/Darth_Vader
https://en.wikipedia.org/wiki/Lionel_Messi
https://en.wikipedia.org/wiki/Star_Wars
https://en.wikipedia.org/wiki/Miley_Cyrus
https://en.wikipedia.org/wiki/List_of_Presidents_of_the_United_States
https://en.wikipedia.org/wiki/Harry_Potter
https://en.wikipedia.org/wiki/Talk:Main_Page
https://en.wikipedia.org/wiki/Japan
https://en.wikipedia.org/wiki/Germany
https://en.wikipedia.org/wiki/Rihanna
https://en.wikipedia.org/wiki/Selena_Gomez
https://en.wikipedia.org/wiki/Taylor_Swift
https://en.wikipedia.org/wiki/The_Walking_Dead_(TV_series)
https://en.wikipedia.org/wiki/Abraham_Lincoln
https://en.wikipedia.org/wiki/China
https://en.wikipedia.org/wiki/Wikipedia:Special:Export
https://en.wikipedia.org/wiki/Dwayne_Johnson
https://en.wikipedia.org/wiki/Johnny_Depp
https://en.wikipedia.org/wiki/New_York_City
https://en.wikipedia.org/wiki/Russia
https://en.wikipedia.org/wiki/Albert_Einstein
https://en.wikipedia.org/wiki/Glee_(TV_series)
https://en.wikipedia.org/wiki/Kanye_West
https://en.wikipedia.org/wiki/Breaking_Bad
https://en.wikipedia.org/wiki/France
https://en.wikipedia.org/wiki/Tupac_Shakur
https://en.wikipedia.org/wiki/Michael_Jordan
https://en.wikipedia.org/wiki/Angelina_Jolie
https://en.wikipedia.org/wiki/Earth
https://en.wikipedia.org/wiki/Indigenous_australian
https://en.wikipedia.org/wiki/Mark_Zuckerberg
https://en.wikipedia.org/wiki/Leonardo_DiCaprio
https://en.wikipedia.org/wiki/William_Shakespeare
https://en.wikipedia.org/wiki/Vietnam_War
https://en.wikipedia.org/wiki/John_F._Kennedy
https://en.wikipedia.org/wiki/Nicki_Minaj
https://en.wikipedia.org/wiki/Mila_Kunis
https://en.wikipedia.org/wiki/Wikipedia:Contact_us
https://en.wikipedia.org/wiki/LeBron_James
https://en.wikipedia.org/wiki/Web_scraping
https://en.wikipedia.org/wiki/Illuminati
https://en.wikipedia.org/wiki/John_Cena
https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Articles_for_creation/Help_desk
https://en.wikipedia.org/wiki/September_11_attacks
https://en.wikipedia.org/wiki/Katy_Perry
https://en.wikipedia.org/wiki/Sexual_intercourse
https://en.wikipedia.org/wiki/Tom_Cruise
https://en.wikipedia.org/wiki/Doctor_Who
https://en.wikipedia.org/wiki/Bill_Gates
https://en.wikipedia.org/wiki/List_of_highest-grossing_films
https://en.wikipedia.org/wiki/Pablo_Escobar
https://en.wikipedia.org/wiki/Will_Smith
https://en.wikipedia.org/wiki/Arnold_Schwarzenegger
https://en.wikipedia.org/wiki/Muhammad_Ali
https://en.wikipedia.org/wiki/Adele
https://en.wikipedia.org/wiki/Human_penis_size
https://en.wikipedia.org/wiki/AMGTV
https://en.wikipedia.org/wiki/Internet_Movie_Database
https://en.wikipedia.org/wiki/Portal:Featured_content
https://en.wikipedia.org/wiki/Jay-Z
https://en.wikipedia.org/wiki/London
https://en.wikipedia.org/wiki/Singapore
https://en.wikipedia.org/wiki/Israel
https://en.wikipedia.org/wiki/Global_warming
https://en.wikipedia.org/wiki/One_Direction
https://en.wikipedia.org/wiki/Halloween
https://en.wikipedia.org/wiki/Bruce_Lee
https://en.wikipedia.org/wiki/Prince_(musician)
https://en.wikipedia.org/wiki/Marilyn_Monroe
https://en.wikipedia.org/wiki/Vagina
https://en.wikipedia.org/wiki/England
https://en.wikipedia.org/wiki/Grey%27s_Anatomy
https://en.wikipedia.org/wiki/RMS_Titanic
https://en.wikipedia.org/wiki/Elvis_Presley
https://en.wikipedia.org/wiki/Scarlett_Johansson
https://en.wikipedia.org/wiki/Pornography
https://en.wikipedia.org/wiki/Jennifer_Aniston
https://en.wikipedia.org/wiki/David_Bowie
https://en.wikipedia.org/wiki/Britney_Spears
https://en.wikipedia.org/wiki/Charles_Manson
https://en.wikipedia.org/wiki/American_Civil_War
https://en.wikipedia.org/wiki/Brazil
https://en.wikipedia.org/wiki/Google
https://en.wikipedia.org/wiki/Wiki
https://en.wikipedia.org/wiki/YouTube
https://en.wikipedia.org/wiki/Facebook
https://en.wikipedia.org/wiki/Australia
https://en.wikipedia.org/wiki/Indigenous_australian
https://en.wikipedia.org/wiki/Aboriginal_Australian
https://en.wikipedia.org/wiki/Member_states_of_the_United_Nations
https://en.wikipedia.org/wiki/United_States
https://en.wikipedia.org/wiki/India
https://en.wikipedia.org/wiki/United_Kingdom
https://en.wikipedia.org/wiki/Canada
https://en.wikipedia.org/wiki/Australia
https://en.wikipedia.org/wiki/Japan
https://en.wikipedia.org/wiki/Germany
https://en.wikipedia.org/wiki/China
https://en.wikipedia.org/wiki/Russia
https://en.wikipedia.org/wiki/France
https://en.wikipedia.org/wiki/Singapore
https://en.wikipedia.org/wiki/Israel
https://en.wikipedia.org/wiki/Brazil
https://en.wikipedia.org/wiki/Italy
https://en.wikipedia.org/wiki/Philippines
https://en.wikipedia.org/wiki/Spain
https://en.wikipedia.org/wiki/Netherlands
https://en.wikipedia.org/wiki/New_Zealand
https://en.wikipedia.org/wiki/Turkey
https://en.wikipedia.org/wiki/Mexico
https://en.wikipedia.org/wiki/Pakistan
https://en.wikipedia.org/wiki/South_Africa
https://en.wikipedia.org/wiki/Indonesia
https://en.wikipedia.org/wiki/North_Korea
https://en.wikipedia.org/wiki/Switzerland
https://en.wikipedia.org/wiki/Egypt
https://en.wikipedia.org/wiki/Sweden
https://en.wikipedia.org/wiki/Greece
https://en.wikipedia.org/wiki/Iran
https://en.wikipedia.org/wiki/Ireland
https://en.wikipedia.org/wiki/New_York_City
https://en.wikipedia.org/wiki/London
https://en.wikipedia.org/wiki/Singapore
https://en.wikipedia.org/wiki/Angelsberg
https://en.wikipedia.org/wiki/Hong_Kong
https://en.wikipedia.org/wiki/Los_Angeles
https://en.wikipedia.org/wiki/Paris
https://en.wikipedia.org/wiki/Chicago
https://en.wikipedia.org/wiki/Washington,_D.C.
https://en.wikipedia.org/wiki/San_Francisco
https://en.wikipedia.org/wiki/Rome
https://en.wikipedia.org/wiki/Mumbai
https://en.wikipedia.org/wiki/Toronto
https://en.wikipedia.org/wiki/Philadelphia
https://en.wikipedia.org/wiki/Monaco
https://en.wikipedia.org/wiki/Amsterdam
https://en.wikipedia.org/wiki/Tokyo
https://en.wikipedia.org/wiki/Boston
https://en.wikipedia.org/wiki/Barcelona
https://en.wikipedia.org/wiki/Istanbul
https://en.wikipedia.org/wiki/Berlin
https://en.wikipedia.org/wiki/Pompeii
https://en.wikipedia.org/wiki/Rio_de_Janeiro
https://en.wikipedia.org/wiki/Seattle
https://en.wikipedia.org/wiki/Venice
https://en.wikipedia.org/wiki/Sparta
https://en.wikipedia.org/wiki/Shanghai
https://en.wikipedia.org/wiki/Vancouver
https://en.wikipedia.org/wiki/Jerusalem
https://en.wikipedia.org/wiki/Macau
https://en.wikipedia.org/wiki/Montreal
https://en.wikipedia.org/wiki/Angelsberg
https://en.wikipedia.org/wiki/Main_page
https://en.wikipedia.org/wiki/Donald_Trump
https://en.wikipedia.org/wiki/Donald_Trump
https://en.wikipedia.org/wiki/Barack_Obama
https://en.wikipedia.org/wiki/Michael_Jackson
https://en.wikipedia.org/wiki/Lady_Gaga
https://en.wikipedia.org/wiki/Eminem
https://en.wikipedia.org/wiki/Adolf_Hitler
https://en.wikipedia.org/wiki/Justin_Bieber
https://en.wikipedia.org/wiki/Steve_Jobs
https://en.wikipedia.org/wiki/Lil_Wayne
https://en.wikipedia.org/wiki/Kim_Kardashian
https://en.wikipedia.org/wiki/Cristiano_Ronaldo
https://en.wikipedia.org/wiki/Miley_Cyrus
https://en.wikipedia.org/wiki/Elizabeth_II
https://en.wikipedia.org/wiki/Rihanna
https://en.wikipedia.org/wiki/Selena_Gomez
https://en.wikipedia.org/wiki/Abraham_Lincoln
https://en.wikipedia.org/wiki/Taylor_Swift
https://en.wikipedia.org/wiki/Lionel_Messi
https://en.wikipedia.org/wiki/Johnny_Depp
https://en.wikipedia.org/wiki/Tupac_Shakur
https://en.wikipedia.org/wiki/Kanye_West
https://en.wikipedia.org/wiki/Stephen_Hawking
https://en.wikipedia.org/wiki/Albert_Einstein
https://en.wikipedia.org/wiki/Angelina_Jolie
https://en.wikipedia.org/wiki/Mark_Zuckerberg
https://en.wikipedia.org/wiki/Leonardo_DiCaprio
https://en.wikipedia.org/wiki/Nicki_Minaj
https://en.wikipedia.org/wiki/William_Shakespeare
https://en.wikipedia.org/wiki/Michael_Jordan
https://en.wikipedia.org/wiki/Dwayne_Johnson
https://en.wikipedia.org/wiki/Michael_Jackson
https://en.wikipedia.org/wiki/Lady_Gaga
https://en.wikipedia.org/wiki/Eminem
https://en.wikipedia.org/wiki/Justin_Bieber
https://en.wikipedia.org/wiki/Lil_Wayne
https://en.wikipedia.org/wiki/Miley_Cyrus
https://en.wikipedia.org/wiki/Rihanna
https://en.wikipedia.org/wiki/Selena_Gomez
https://en.wikipedia.org/wiki/Taylor_Swift
https://en.wikipedia.org/wiki/Tupac_Shakur
https://en.wikipedia.org/wiki/Kanye_West
https://en.wikipedia.org/wiki/Nicki_Minaj
https://en.wikipedia.org/wiki/Katy_Perry
https://en.wikipedia.org/wiki/Adele
https://en.wikipedia.org/wiki/John_Cena
https://en.wikipedia.org/wiki/Jay-Z
https://en.wikipedia.org/wiki/Prince_(musician)
https://en.wikipedia.org/wiki/David_Bowie
https://en.wikipedia.org/wiki/Britney_Spears
https://en.wikipedia.org/wiki/Elvis_Presley
https://en.wikipedia.org/wiki/Beyonc%C3%A9_Knowles
https://en.wikipedia.org/wiki/Madonna_(entertainer)
https://en.wikipedia.org/wiki/Bob_Marley
https://en.wikipedia.org/wiki/Ariana_Grande
https://en.wikipedia.org/wiki/John_Lennon
https://en.wikipedia.org/wiki/Demi_Lovato
https://en.wikipedia.org/wiki/Mariah_Carey
https://en.wikipedia.org/wiki/Bruno_Mars
https://en.wikipedia.org/wiki/50_Cent
https://en.wikipedia.org/wiki/Freddie_Mercury
https://en.wikipedia.org/wiki/Kim_Kardashian
https://en.wikipedia.org/wiki/Johnny_Depp
https://en.wikipedia.org/wiki/Angelina_Jolie
https://en.wikipedia.org/wiki/Leonardo_DiCaprio
https://en.wikipedia.org/wiki/Dwayne_Johnson
https://en.wikipedia.org/wiki/Mila_Kunis
https://en.wikipedia.org/wiki/Arnold_Schwarzenegger
https://en.wikipedia.org/wiki/Will_Smith
https://en.wikipedia.org/wiki/Bruce_Lee
https://en.wikipedia.org/wiki/Marilyn_Monroe
https://en.wikipedia.org/wiki/Tom_Cruise
https://en.wikipedia.org/wiki/Scarlett_Johansson
https://en.wikipedia.org/wiki/Megan_Fox
https://en.wikipedia.org/wiki/Jennifer_Aniston
https://en.wikipedia.org/wiki/The_Undertaker
https://en.wikipedia.org/wiki/Jennifer_Lawrence
https://en.wikipedia.org/wiki/Brad_Pitt
https://en.wikipedia.org/wiki/Emma_Watson
https://en.wikipedia.org/wiki/Heath_Ledger
https://en.wikipedia.org/wiki/Sunny_Leone
https://en.wikipedia.org/wiki/Mark_Wahlberg
https://en.wikipedia.org/wiki/Kristen_Stewart
https://en.wikipedia.org/wiki/Ryan_Reynolds
https://en.wikipedia.org/wiki/Charlie_Sheen
https://en.wikipedia.org/wiki/Sylvester_Stallone
https://en.wikipedia.org/wiki/Robin_Williams
https://en.wikipedia.org/wiki/Natalie_Portman
https://en.wikipedia.org/wiki/Clint_Eastwood
https://en.wikipedia.org/wiki/Tom_Hardy
https://en.wikipedia.org/wiki/Emma_Stone
https://en.wikipedia.org/wiki/Bruce_Lee
https://en.wikipedia.org/wiki/Arnold_Schwarzenegger
https://en.wikipedia.org/wiki/Dwayne_Johnson
https://en.wikipedia.org/wiki/The_Undertaker
https://en.wikipedia.org/wiki/John_Cena
https://en.wikipedia.org/wiki/Cristiano_Ronaldo
https://en.wikipedia.org/wiki/Association_football
https://en.wikipedia.org/wiki/Lionel_Messi
https://en.wikipedia.org/wiki/Association_football
https://en.wikipedia.org/wiki/Michael_Jordan
https://en.wikipedia.org/wiki/Basketball
https://en.wikipedia.org/wiki/Muhammad_Ali
https://en.wikipedia.org/wiki/Professional_boxing
https://en.wikipedia.org/wiki/LeBron_James
https://en.wikipedia.org/wiki/Basketball
https://en.wikipedia.org/wiki/Kobe_Bryant
https://en.wikipedia.org/wiki/Basketball
https://en.wikipedia.org/wiki/O._J._Simpson
https://en.wikipedia.org/wiki/American_football
https://en.wikipedia.org/wiki/Roger_Federer
https://en.wikipedia.org/wiki/Tennis
https://en.wikipedia.org/wiki/Tom_Brady
https://en.wikipedia.org/wiki/American_football
https://en.wikipedia.org/wiki/Brock_Lesnar
https://en.wikipedia.org/wiki/Professional_wrestling
https://en.wikipedia.org/wiki/Mixed_martial_arts
https://en.wikipedia.org/wiki/Mike_Tyson
https://en.wikipedia.org/wiki/Professional_boxing
https://en.wikipedia.org/wiki/Michael_Phelps
https://en.wikipedia.org/wiki/Swimming_(sport)
https://en.wikipedia.org/wiki/David_Beckham
https://en.wikipedia.org/wiki/Association_football
https://en.wikipedia.org/wiki/Shaquille_O%27Neal
https://en.wikipedia.org/wiki/Basketball
https://en.wikipedia.org/wiki/Manny_Pacquiao
https://en.wikipedia.org/wiki/Professional_boxing
https://en.wikipedia.org/wiki/Peyton_Manning
https://en.wikipedia.org/wiki/American_football
https://en.wikipedia.org/wiki/Rafael_Nadal
https://en.wikipedia.org/wiki/Tennis
https://en.wikipedia.org/wiki/Sachin_Tendulkar
https://en.wikipedia.org/wiki/Cricket
https://en.wikipedia.org/wiki/Neymar
https://en.wikipedia.org/wiki/Association_football
https://en.wikipedia.org/wiki/Conor_McGregor
https://en.wikipedia.org/wiki/Mixed_martial_arts
https://en.wikipedia.org/wiki/Usain_Bolt
https://en.wikipedia.org/wiki/Sprint_(running)
https://en.wikipedia.org/wiki/Tiger_Woods
https://en.wikipedia.org/wiki/Golf
https://en.wikipedia.org/wiki/Zlatan_Ibrahimovi%C4%87
https://en.wikipedia.org/wiki/Association_football
https://en.wikipedia.org/wiki/Serena_Williams
https://en.wikipedia.org/wiki/Tennis
https://en.wikipedia.org/wiki/Floyd_Mayweather,_Jr.
https://en.wikipedia.org/wiki/Professional_boxing
https://en.wikipedia.org/wiki/Ronaldinho
https://en.wikipedia.org/wiki/Association_football
https://en.wikipedia.org/wiki/Ronda_Rousey
https://en.wikipedia.org/wiki/Judo
https://en.wikipedia.org/wiki/Mixed_martial_arts
https://en.wikipedia.org/wiki/Wayne_Rooney
https://en.wikipedia.org/wiki/Association_football
https://en.wikipedia.org/wiki/Novak_Djokovic
https://en.wikipedia.org/wiki/Tennis
https://en.wikipedia.org/wiki/Ronaldo
https://en.wikipedia.org/wiki/Association_football
https://en.wikipedia.org/wiki/Vladimir_Putin
https://en.wikipedia.org/wiki/Sarah_Palin
https://en.wikipedia.org/wiki/Donald_Trump
https://en.wikipedia.org/wiki/Barack_Obama
https://en.wikipedia.org/wiki/Adolf_Hitler
https://en.wikipedia.org/wiki/Elizabeth_II
https://en.wikipedia.org/wiki/Abraham_Lincoln
https://en.wikipedia.org/wiki/John_F._Kennedy
https://en.wikipedia.org/wiki/Henry_VIII_of_England
https://en.wikipedia.org/wiki/Nelson_Mandela
https://en.wikipedia.org/wiki/George_W._Bush
https://en.wikipedia.org/wiki/Ronald_Reagan
https://en.wikipedia.org/wiki/Queen_Victoria
https://en.wikipedia.org/wiki/Bill_Clinton
https://en.wikipedia.org/wiki/George_Washington
https://en.wikipedia.org/wiki/Osama_bin_Laden
https://en.wikipedia.org/wiki/Franklin_D._Roosevelt
https://en.wikipedia.org/wiki/Elizabeth_I
https://en.wikipedia.org/wiki/Winston_Churchill
https://en.wikipedia.org/wiki/Mahatma_Gandhi
https://en.wikipedia.org/wiki/Christopher_Columbus
https://en.wikipedia.org/wiki/Che_Guevara
https://en.wikipedia.org/wiki/Joseph_Stalin
https://en.wikipedia.org/wiki/Richard_Nixon
https://en.wikipedia.org/wiki/Vladimir_Putin
https://en.wikipedia.org/wiki/Charles,_Prince_of_Wales
https://en.wikipedia.org/wiki/Prince_Philip,_Duke_of_Edinburgh
https://en.wikipedia.org/wiki/Sarah_Palin
https://en.wikipedia.org/wiki/Theodore_Roosevelt
https://en.wikipedia.org/wiki/Thomas_Jefferson
https://en.wikipedia.org/wiki/Benjamin_Franklin
https://en.wikipedia.org/wiki/George_H._W._Bush
https://en.wikipedia.org/wiki/Margaret_Thatcher
https://en.wikipedia.org/wiki/Joan_of_Arc
https://en.wikipedia.org/wiki/Jesus
https://en.wikipedia.org/wiki/Alexander_the_Great
https://en.wikipedia.org/wiki/Muhammad
https://en.wikipedia.org/wiki/Julius_Caesar
https://en.wikipedia.org/wiki/Genghis_Khan
https://en.wikipedia.org/wiki/Aristotle
https://en.wikipedia.org/wiki/Gautama_Buddha
https://en.wikipedia.org/wiki/Spartacus
https://en.wikipedia.org/wiki/Plato
https://en.wikipedia.org/wiki/Joan_of_Arc
https://en.wikipedia.org/wiki/Socrates
https://en.wikipedia.org/wiki/Charlemagne
https://en.wikipedia.org/wiki/Tutankhamun
https://en.wikipedia.org/wiki/Marco_Polo
https://en.wikipedia.org/wiki/Moses
https://en.wikipedia.org/wiki/Augustus
https://en.wikipedia.org/wiki/King_Arthur
https://en.wikipedia.org/wiki/William_Wallace
https://en.wikipedia.org/wiki/Robin_Hood
https://en.wikipedia.org/wiki/Cleopatra
https://en.wikipedia.org/wiki/Nero
https://en.wikipedia.org/wiki/Caligula
https://en.wikipedia.org/wiki/Hannibal
https://en.wikipedia.org/wiki/Ragnar_Lodbrok
https://en.wikipedia.org/wiki/Confucius
https://en.wikipedia.org/wiki/Archimedes
https://en.wikipedia.org/wiki/Pythagoras
https://en.wikipedia.org/wiki/Abraham
https://en.wikipedia.org/wiki/Asoka
https://en.wikipedia.org/wiki/Richard_I_of_England
https://en.wikipedia.org/wiki/David
https://en.wikipedia.org/wiki/Princess_Elisabeth,_Duchess_of_Brabant
https://en.wikipedia.org/wiki/Lady_Louise_Windsor
https://en.wikipedia.org/wiki/Catharina-Amalia,_Princess_of_Orange
https://en.wikipedia.org/wiki/Willow_Smith
https://en.wikipedia.org/wiki/Jackie_Evancho
https://en.wikipedia.org/wiki/Laurie_Hernandez
https://en.wikipedia.org/wiki/LaMelo_Ball
https://en.wikipedia.org/wiki/Willow_Smith
https://en.wikipedia.org/wiki/Millie_Bobby_Brown
https://en.wikipedia.org/wiki/Maddie_Ziegler
https://en.wikipedia.org/wiki/Prince_George_of_Cambridge
https://en.wikipedia.org/wiki/Noah_Cyrus
https://en.wikipedia.org/wiki/Lil_Pump
https://en.wikipedia.org/wiki/Jackie_Evancho
https://en.wikipedia.org/wiki/Lady_Louise_Windsor
https://en.wikipedia.org/wiki/Princess_Charlotte_of_Cambridge
https://en.wikipedia.org/wiki/Mackenzie_Foy
https://en.wikipedia.org/wiki/Gaten_Matarazzo
https://en.wikipedia.org/wiki/Finn_Wolfhard
https://en.wikipedia.org/wiki/James,_Viscount_Severn
https://en.wikipedia.org/wiki/Jacob_Tremblay
https://en.wikipedia.org/wiki/Rowan_Blanchard
https://en.wikipedia.org/wiki/Auli%27i_Cravalho
https://en.wikipedia.org/wiki/Skai_Jackson
https://en.wikipedia.org/wiki/Danielle_Bregoli
https://en.wikipedia.org/wiki/LaMelo_Ball
https://en.wikipedia.org/wiki/Yara_Shahidi
https://en.wikipedia.org/wiki/Jazz_Jennings
https://en.wikipedia.org/wiki/Madison_De_La_Garza
https://en.wikipedia.org/wiki/Quvenzhan%C3%A9_Wallis
https://en.wikipedia.org/wiki/Dafne_Keen
https://en.wikipedia.org/wiki/Zaira_Wasim
https://en.wikipedia.org/wiki/Connie_Talbot
https://en.wikipedia.org/wiki/Harshaali_Malhotra
https://en.wikipedia.org/wiki/Grace_VanderWaal
https://en.wikipedia.org/wiki/Willow_Shields
https://en.wikipedia.org/wiki/Laurie_Hernandez
https://en.wikipedia.org/wiki/David_Mazouz
https://en.wikipedia.org/wiki/Jaeden_Lieberher
https://en.wikipedia.org/wiki/The_Beatles
https://en.wikipedia.org/wiki/One_Direction
https://en.wikipedia.org/wiki/Metallica
https://en.wikipedia.org/wiki/Pink_Floyd
https://en.wikipedia.org/wiki/Linkin_Park
https://en.wikipedia.org/wiki/Red_Hot_Chili_Peppers
https://en.wikipedia.org/wiki/Led_Zeppelin
https://en.wikipedia.org/wiki/Coldplay
https://en.wikipedia.org/wiki/Queen_(band)
https://en.wikipedia.org/wiki/AC/DC
https://en.wikipedia.org/wiki/Daft_Punk
https://en.wikipedia.org/wiki/Slipknot_(band)
https://en.wikipedia.org/wiki/Nirvana_(band)
https://en.wikipedia.org/wiki/Green_Day
https://en.wikipedia.org/wiki/The_Rolling_Stones
https://en.wikipedia.org/wiki/Guns_N%27_Roses
https://en.wikipedia.org/wiki/Girls%27_Generation
https://en.wikipedia.org/wiki/Gorillaz
https://en.wikipedia.org/wiki/Iron_Maiden
https://en.wikipedia.org/wiki/Jonas_Brothers
https://en.wikipedia.org/wiki/Foo_Fighters
https://en.wikipedia.org/wiki/Kiss_(band)
https://en.wikipedia.org/wiki/Spice_Girls
https://en.wikipedia.org/wiki/Avenged_Sevenfold
https://en.wikipedia.org/wiki/Radiohead
https://en.wikipedia.org/wiki/Muse_(band)
https://en.wikipedia.org/wiki/Paramore
https://en.wikipedia.org/wiki/Backstreet_Boys
https://en.wikipedia.org/wiki/Maroon_5
https://en.wikipedia.org/wiki/Blink-182
https://en.wikipedia.org/wiki/Bee_Gees
https://en.wikipedia.org/wiki/U2
https://en.wikipedia.org/wiki/Association_football
https://en.wikipedia.org/wiki/Golden_State_Warriors
https://en.wikipedia.org/wiki/Manchester_United_F.C.
https://en.wikipedia.org/wiki/FC_Barcelona
https://en.wikipedia.org/wiki/Chelsea_F.C.
https://en.wikipedia.org/wiki/Arsenal_F.C.
https://en.wikipedia.org/wiki/Real_Madrid_C.F.
https://en.wikipedia.org/wiki/Liverpool_F.C.
https://en.wikipedia.org/wiki/Manchester_City_F.C.
https://en.wikipedia.org/wiki/Brazil_national_football_team
https://en.wikipedia.org/wiki/A.C._Milan
https://en.wikipedia.org/wiki/Tottenham_Hotspur_F.C.
https://en.wikipedia.org/wiki/England_national_football_team
https://en.wikipedia.org/wiki/Germany_national_football_team
https://en.wikipedia.org/wiki/Juventus_F.C.
https://en.wikipedia.org/wiki/FC_Bayern_Munich
https://en.wikipedia.org/wiki/New_England_Patriots
https://en.wikipedia.org/wiki/Spain_national_football_team
https://en.wikipedia.org/wiki/Los_Angeles_Lakers
https://en.wikipedia.org/wiki/Borussia_Dortmund
https://en.wikipedia.org/wiki/Argentina_national_football_team
https://en.wikipedia.org/wiki/Golden_State_Warriors
https://en.wikipedia.org/wiki/Italy_national_football_team
https://en.wikipedia.org/wiki/France_national_football_team
https://en.wikipedia.org/wiki/Newcastle_United_F.C.
https://en.wikipedia.org/wiki/West_Ham_United_F.C.
https://en.wikipedia.org/wiki/Netherlands_national_football_team
https://en.wikipedia.org/wiki/New_York_Yankees
https://en.wikipedia.org/wiki/Paris_Saint-Germain_F.C.
https://en.wikipedia.org/wiki/Aston_Villa_F.C.
https://en.wikipedia.org/wiki/Leicester_City_F.C.
https://en.wikipedia.org/wiki/Miami_Heat
https://en.wikipedia.org/wiki/Chicago_Bulls
https://en.wikipedia.org/wiki/Rangers_F.C.
https://en.wikipedia.org/wiki/Celtic_F.C.
https://en.wikipedia.org/wiki/Oakland_Raiders
https://en.wikipedia.org/wiki/The_Big_Bang_Theory
https://en.wikipedia.org/wiki/Game_of_Thrones
https://en.wikipedia.org/wiki/How_I_Met_Your_Mother
https://en.wikipedia.org/wiki/Glee_(TV_series)
https://en.wikipedia.org/wiki/The_Walking_Dead_(TV_series)
https://en.wikipedia.org/wiki/Star_Wars
https://en.wikipedia.org/wiki/Breaking_Bad
https://en.wikipedia.org/wiki/Doctor_Who
https://en.wikipedia.org/wiki/Grey%27s_Anatomy
https://en.wikipedia.org/wiki/Lost_(TV_series)
https://en.wikipedia.org/wiki/Dexter_(TV_series)
https://en.wikipedia.org/wiki/Naruto
https://en.wikipedia.org/wiki/Family_Guy
https://en.wikipedia.org/wiki/The_Avengers_(2012_film)
https://en.wikipedia.org/wiki/House_(TV_series)
https://en.wikipedia.org/wiki/Avatar_(2009_film)
https://en.wikipedia.org/wiki/True_Blood
https://en.wikipedia.org/wiki/The_Dark_Knight_Rises
https://en.wikipedia.org/wiki/Friends
https://en.wikipedia.org/wiki/Two_and_a_Half_Men
https://en.wikipedia.org/wiki/Sons_of_Anarchy
https://en.wikipedia.org/wiki/The_Vampire_Diaries
https://en.wikipedia.org/wiki/Arrow_(TV_series)
https://en.wikipedia.org/wiki/Sherlock_(TV_series)
https://en.wikipedia.org/wiki/The_Office_(U.S._TV_series)
https://en.wikipedia.org/wiki/Once_Upon_a_Time_(TV_series)
https://en.wikipedia.org/wiki/The_Simpsons
https://en.wikipedia.org/wiki/South_Park
https://en.wikipedia.org/wiki/NCIS_(TV_series)
https://en.wikipedia.org/wiki/Titanic_(1997_film)
https://en.wikipedia.org/wiki/Thriller_(Michael_Jackson_album)
https://en.wikipedia.org/wiki/Michael_Jackson
https://en.wikipedia.org/wiki/Sgt._Pepper%27s_Lonely_Hearts_Club_Band
https://en.wikipedia.org/wiki/Beatles
https://en.wikipedia.org/wiki/Recovery_(Eminem_album)
https://en.wikipedia.org/wiki/Eminem
https://en.wikipedia.org/wiki/The_Dark_Side_of_the_Moon
https://en.wikipedia.org/wiki/Pink_Floyd
https://en.wikipedia.org/wiki/My_Beautiful_Dark_Twisted_Fantasy
https://en.wikipedia.org/wiki/Kanye_West
https://en.wikipedia.org/wiki/21_(Adele_album)
https://en.wikipedia.org/wiki/Adele
https://en.wikipedia.org/wiki/The_Beatles_(album)
https://en.wikipedia.org/wiki/Beatles
https://en.wikipedia.org/wiki/The_Wall
https://en.wikipedia.org/wiki/Pink_Floyd
https://en.wikipedia.org/wiki/Abbey_Road
https://en.wikipedia.org/wiki/Beatles
https://en.wikipedia.org/wiki/Watch_the_Throne
https://en.wikipedia.org/wiki/Jay-Z
https://en.wikipedia.org/wiki/Kanye_West
https://en.wikipedia.org/wiki/Nevermind
https://en.wikipedia.org/wiki/Nirvana
https://en.wikipedia.org/wiki/The_Marshall_Mathers_LP
https://en.wikipedia.org/wiki/Eminem
https://en.wikipedia.org/wiki/808s_%26_Heartbreak
https://en.wikipedia.org/wiki/Kanye_West
https://en.wikipedia.org/wiki/Teenage_Dream_(Katy_Perry_album)
https://en.wikipedia.org/wiki/Katy_Perry
https://en.wikipedia.org/wiki/Loud_(Rihanna_album)
https://en.wikipedia.org/wiki/Rihanna
https://en.wikipedia.org/wiki/Led_Zeppelin_IV
https://en.wikipedia.org/wiki/Led_Zeppelin
https://en.wikipedia.org/wiki/Graduation_(album)
https://en.wikipedia.org/wiki/Kanye_West
https://en.wikipedia.org/wiki/Let_It_Be
https://en.wikipedia.org/wiki/Beatles
https://en.wikipedia.org/wiki/The_Eminem_Show
https://en.wikipedia.org/wiki/Eminem
https://en.wikipedia.org/wiki/The_Slim_Shady_LP
https://en.wikipedia.org/wiki/Eminem
https://en.wikipedia.org/wiki/Fearless_(Taylor_Swift_album)
https://en.wikipedia.org/wiki/Taylor_Swift
https://en.wikipedia.org/wiki/Circus_(Britney_Spears_album)
https://en.wikipedia.org/wiki/Britney_Spears
https://en.wikipedia.org/wiki/Red_(Taylor_Swift_album)
https://en.wikipedia.org/wiki/Taylor_Swift
https://en.wikipedia.org/wiki/Metallica_(album)
https://en.wikipedia.org/wiki/Metallica
https://en.wikipedia.org/wiki/Good_Kid,_M.A.A.D_City
https://en.wikipedia.org/wiki/Kendrick_Lamar
https://en.wikipedia.org/wiki/The_Fame
https://en.wikipedia.org/wiki/Lady_Gaga
https://en.wikipedia.org/wiki/Rubber_Soul
https://en.wikipedia.org/wiki/Beatles
https://en.wikipedia.org/wiki/Hybrid_Theory
https://en.wikipedia.org/wiki/Linkin_Park
https://en.wikipedia.org/wiki/Bad_(album)
https://en.wikipedia.org/wiki/Michael_Jackson
https://en.wikipedia.org/wiki/Yeezus
https://en.wikipedia.org/wiki/Kanye_West
https://en.wikipedia.org/wiki/1989_(Taylor_Swift_album)
https://en.wikipedia.org/wiki/Taylor_Swift
https://en.wikipedia.org/wiki/Naruto
https://en.wikipedia.org/wiki/Anime
https://en.wikipedia.org/wiki/Manga
https://en.wikipedia.org/wiki/A_Song_of_Ice_and_Fire
https://en.wikipedia.org/wiki/Game_of_Thrones
https://en.wikipedia.org/wiki/Harry_Potter
https://en.wikipedia.org/wiki/Fifty_Shades_of_Grey
https://en.wikipedia.org/wiki/The_Hunger_Games
https://en.wikipedia.org/wiki/A_Song_of_Ice_and_Fire
https://en.wikipedia.org/wiki/The_Great_Gatsby
https://en.wikipedia.org/wiki/The_Lord_of_the_Rings
https://en.wikipedia.org/wiki/A_Game_of_Thrones
https://en.wikipedia.org/wiki/Nineteen_Eighty-Four
https://en.wikipedia.org/wiki/Kama_Sutra
https://en.wikipedia.org/wiki/Alice%27s_Adventures_in_Wonderland
https://en.wikipedia.org/wiki/Les_Mis%C3%A9rables
https://en.wikipedia.org/wiki/To_Kill_a_Mockingbird
https://en.wikipedia.org/wiki/Harry_Potter_and_the_Deathly_Hallows
https://en.wikipedia.org/wiki/The_Girl_with_the_Dragon_Tattoo
https://en.wikipedia.org/wiki/Watchmen
https://en.wikipedia.org/wiki/The_Winds_of_Winter
https://en.wikipedia.org/wiki/The_Catcher_in_the_Rye
https://en.wikipedia.org/wiki/Sex_(book)
https://en.wikipedia.org/wiki/Pride_and_Prejudice
https://en.wikipedia.org/wiki/The_Hobbit
https://en.wikipedia.org/wiki/Inferno_(Dante)
https://en.wikipedia.org/wiki/Code_Geass
https://en.wikipedia.org/wiki/Lolita
https://en.wikipedia.org/wiki/Frankenstein
https://en.wikipedia.org/wiki/Bible
https://en.wikipedia.org/wiki/The_Picture_of_Dorian_Gray
https://en.wikipedia.org/wiki/Dracula
https://en.wikipedia.org/wiki/Animal_Farm
https://en.wikipedia.org/wiki/Of_Mice_and_Men
https://en.wikipedia.org/wiki/Brave_New_World
https://en.wikipedia.org/wiki/American_Idiot
https://en.wikipedia.org/wiki/Porno_(novel)
https://en.wikipedia.org/wiki/Bible
https://en.wikipedia.org/wiki/List_of_best-selling_books
https://en.wikipedia.org/wiki/Quran
https://en.wikipedia.org/wiki/Kama_Sutra
https://en.wikipedia.org/wiki/History_of_India
https://en.wikipedia.org/wiki/Inferno_(Dante)
https://en.wikipedia.org/wiki/Italy_in_the_Middle_Ages
https://en.wikipedia.org/wiki/Bible
https://en.wikipedia.org/wiki/History_of_ancient_Israel_and_Judah
https://en.wikipedia.org/wiki/Odyssey
https://en.wikipedia.org/wiki/Ancient_Greece
https://en.wikipedia.org/wiki/Rosetta_Stone
https://en.wikipedia.org/wiki/Ancient_Egypt
https://en.wikipedia.org/wiki/Beowulf
https://en.wikipedia.org/wiki/England_in_the_Middle_Ages
https://en.wikipedia.org/wiki/Divine_Comedy
https://en.wikipedia.org/wiki/Italy_in_the_Middle_Ages
https://en.wikipedia.org/wiki/Quran
https://en.wikipedia.org/wiki/Caliphate
https://en.wikipedia.org/wiki/Iliad
https://en.wikipedia.org/wiki/Ancient_Greece
https://en.wikipedia.org/wiki/Mahabharata
https://en.wikipedia.org/wiki/History_of_India
https://en.wikipedia.org/wiki/The_Art_of_War
https://en.wikipedia.org/wiki/History_of_China
https://en.wikipedia.org/wiki/Ramayana
https://en.wikipedia.org/wiki/History_of_India
https://en.wikipedia.org/wiki/Epic_of_Gilgamesh
https://en.wikipedia.org/wiki/Mesopotamia
https://en.wikipedia.org/wiki/The_Canterbury_Tales
https://en.wikipedia.org/wiki/England_in_the_Middle_Ages
https://en.wikipedia.org/wiki/Vedas
https://en.wikipedia.org/wiki/History_of_India
https://en.wikipedia.org/wiki/Talmud
https://en.wikipedia.org/wiki/Judaism
https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights
https://en.wikipedia.org/wiki/Caliphate
https://en.wikipedia.org/wiki/Code_of_Hammurabi
https://en.wikipedia.org/wiki/Mesopotamia
https://en.wikipedia.org/wiki/I_Ching
https://en.wikipedia.org/wiki/History_of_China
https://en.wikipedia.org/wiki/Oedipus_the_King
https://en.wikipedia.org/wiki/Ancient_Greece
https://en.wikipedia.org/wiki/Book_of_the_Dead
https://en.wikipedia.org/wiki/Ancient_Egypt
https://en.wikipedia.org/wiki/Aeneid
https://en.wikipedia.org/wiki/Ancient_Rome
https://en.wikipedia.org/wiki/Tao_Te_Ching
https://en.wikipedia.org/wiki/History_of_China
https://en.wikipedia.org/wiki/Domesday_Book
https://en.wikipedia.org/wiki/England_in_the_Middle_Ages
https://en.wikipedia.org/wiki/Rigveda
https://en.wikipedia.org/wiki/History_of_India
https://en.wikipedia.org/wiki/Upanishads
https://en.wikipedia.org/wiki/History_of_India
https://en.wikipedia.org/wiki/Cupid_and_Psyche
https://en.wikipedia.org/wiki/Ancient_Greece
https://en.wikipedia.org/wiki/Lysistrata
https://en.wikipedia.org/wiki/Ancient_Greece
https://en.wikipedia.org/wiki/Titanomachy
https://en.wikipedia.org/wiki/Ancient_Greece
https://en.wikipedia.org/wiki/The_Decameron
https://en.wikipedia.org/wiki/Italy_in_the_Middle_Ages
https://en.wikipedia.org/wiki/Mesoamerican_Long_Count_calendar
https://en.wikipedia.org/wiki/Maya_civilization
https://en.wikipedia.org/wiki/Wikipedia:Most_popular_pages_October_2001
https://en.wikipedia.org/wiki/Wikipedia:Popular_pages
https://en.wikipedia.org/wiki/Wikipedia:Popular_pages
https://en.wikipedia.org/wiki/Wikipedia:Popular_pages
https://en.wikipedia.org/wiki/Wikipedia:Most_read_articles_in_2008
https://en.wikipedia.org/wiki/Wikipedia:Zeitgeist_2008-2013
https://en.wikipedia.org/wiki/Wikipedia:Most_read_articles_in_2009
https://en.wikipedia.org/wiki/Wikipedia:Most_read_articles_in_2010
https://en.wikipedia.org/wiki/User:West.andrew.g/2013_popular_pages
https://en.wikipedia.org/wiki/User:West.andrew.g/2014_Popular_pages
https://en.wikipedia.org/wiki/User:West.andrew.g/2015_Popular_pages
https://en.wikipedia.org/wiki/User:West.andrew.g/2016_Popular_pages
https://en.wikipedia.org/wiki/User:West.andrew.g/2017_Popular_pages
https://en.wikipedia.org/wiki/User:West.andrew.g/Popular_pages
https://en.wikipedia.org/wiki/User:West.andrew.g/2015_Popular_pages
https://en.wikipedia.org/wiki/User:West.andrew.g/2016_Popular_pages
https://en.wikipedia.org/wiki/User:West.andrew.g/2017_Popular_pages
https://en.wikipedia.org/wiki/List_of_most_viewed_YouTube_videos
https://en.wikipedia.org/wiki/Wikipedia:Wikipedia_Signpost/2013-02-04/Special_report
https://en.wikipedia.org/wiki/User:West.andrew.g/2015_Popular_pages
